image: node:20

variables:
  GIT_STRATEGY: fetch

stages:
  - lint
  - test
  - build
  - e2e
  - performance

# ─────────────────────────────────────────────────────────────────────────
# 1) LINT + SECURITY CHECKS
# ─────────────────────────────────────────────────────────────────────────
lint-security:
  stage: lint
  script:
    - npm ci
    - npm run lint:ci

# ─────────────────────────────────────────────────────────────────────────
# 2) VITEST TESTS (UNIT, INTEGRATION, I18N)
# ─────────────────────────────────────────────────────────────────────────
vitest-tests:
  stage: test
  script:
    - npm ci
    - npm run test:unit
    - npm run test:integration
    - npm run test:i18n

# ─────────────────────────────────────────────────────────────────────────
# 3) BUILD NEXT.JS DOCKER IMAGE
# ─────────────────────────────────────────────────────────────────────────
build-nextjs:
  stage: build
  script:
    - npm ci
    - npm run build
    - docker build -t frontend-testing-framework:latest .
    - docker save frontend-testing-framework:latest -o image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day
