image: node:20

variables:
  GIT_STRATEGY: fetch

stages:
  - lint
  - test
  - build
  - e2e
  - performance

# ─────────────────────────────────────────────────────────────────────────
# 1) LINT + SECURITY CHECKS
# ─────────────────────────────────────────────────────────────────────────
lint-security:
  stage: lint
  script:
    - npm ci
    - npm run lint:ci

# ─────────────────────────────────────────────────────────────────────────
# 2) JEST TESTS (UNIT, INTEGRATION, I18N)
# ─────────────────────────────────────────────────────────────────────────
jest-tests:
  stage: test
  script:
    - npm ci
    - npm run test:unit
    - npm run test:integration
    - npm run test:i18n

# ─────────────────────────────────────────────────────────────────────────
# 3) BUILD NEXT.JS
# ─────────────────────────────────────────────────────────────────────────
build-nextjs:
  stage: build
  script:
    - npm ci
    - npm run build
    - tar -czf build_artifacts.tgz .next
  artifacts:
    paths:
      - build_artifacts.tgz
    expire_in: 1 day

# ─────────────────────────────────────────────────────────────────────────
# 4) E2E / VISUAL / ACCESSIBILITY TESTS
# ─────────────────────────────────────────────────────────────────────────
.e2e-test-template: &e2e-test-definition
  stage: e2e
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  dependencies:
    - build-nextjs
  before_script:
    # Remove problematic source lists first
    - rm -f /etc/apt/sources.list.d/microsoft-edge-stable.list /etc/apt/sources.list.d/microsoft-edge.list
    - rm -f /etc/apt/sources.list.d/google-chrome.list
    # Then update and install dependencies
    - apt-get update -y
    - apt-get install -y curl gnupg
    - npm ci
    - tar -xzf build_artifacts.tgz
    - npm start &
    - timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done' || false

e2e-chrome:
  <<: *e2e-test-definition
  script:
    - npm run test:e2e:chrome
    - npm run test:visual:initial
    - npm run test:visual
    - npm run test:accessibility
  artifacts:
    when: always
    paths:
      - ./cypress/screenshots/**/*
      - ./cypress/videos/**/*
    expire_in: 1 week

# e2e-firefox:
#   <<: *e2e-test-definition
#   script:
#     - npm run test:e2e:firefox

# e2e-edge:
#   <<: *e2e-test-definition
#   script:
#     - npm run test:e2e:edge

# e2e-electron:
#   <<: *e2e-test-definition
#   script:
#     - npm run test:e2e:electron

# ─────────────────────────────────────────────────────────────────────────
# 5) PERFORMANCE TESTS (LIGHTHOUSE)
# ─────────────────────────────────────────────────────────────────────────
performance-tests:
  stage: performance
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  dependencies:
    - build-nextjs
  script:
    # Remove problematic source lists first
    - rm -f /etc/apt/sources.list.d/microsoft-edge-stable.list /etc/apt/sources.list.d/microsoft-edge.list
    - rm -f /etc/apt/sources.list.d/google-chrome.list
    # Then update and install dependencies
    - apt-get update -y
    - apt-get install -y curl gnupg chromium-browser
    - npm ci
    - tar -xzf build_artifacts.tgz
    - npm start &
    - timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done' || false
    - mkdir -p ./tmp/artifacts
    - npm install -g lighthouse
    - lighthouse http://localhost:3000 --chrome-flags="--no-sandbox --headless=new" --output json --output html --output-path ./tmp/artifacts/lighthouse-report
  artifacts:
    paths:
      - ./tmp/artifacts
    expire_in: 1 week
